server:
  port: 8081

spring:
  application:
    name: pet-flow-cloud
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://localhost:3306/petflowcloud_database?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: pet_flow_cloud.log
  level:
    web: DEBUG
    org.springframework.boot: DEBUG
    br.com.juhmaran.pet_flow_cloud: INFO